### PR TITLE
Add configuration option to add a path prefix

### PR DESCRIPTION
**Pull request by TimKolberger**
Added `pathPrefix` option.
Added documentation and example Gitlab CI Pages job.
Added a test.

Allows to deploy multiple .md files to Gitlab pages. 
They serve the Gitlab page at `someurl.tld/<project-name>` so with no prefix, additional files would not be reachable.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Timmy!! 👋👋👋

Im gonna take a look tomorrow as it's already 2am 😥

**Comment by SaraVieira** [comment]
Also please add yourself to the contributiors :)

**Comment by SaraVieira** [comment]
Awesome! Thank you so much!


Merged and published in version `fiddly@0.7.4` 🎉

**Comment by TimKolberger** [comment]
Happy birthday 🎉 and thank you 😊

**Pull request merged**
